### ISSUE TITLE
Some mistakes and bugs

### ISSUE THREAD

**Issue by OnTes** [GloriousEggroll/leagueoflegends-linux#1]
I was trying to install this, but I found 2 mistakes in install script at creating desktop entry:
**First**, line 53: My folder where the icon is located is called only "RADS", no "LeaRADS". Maybe it was changed some time ago - I don't know.
And **second**, line 59: I can't understand why there is this line at all. It breaks .desktop file.

After while of playing I discovered that Ctrl/Alt + click (pinging) makes my cursor disappear and super super fast. I know that you probably can't fix this. Its weird but definitely not game breaking bug. 

Thanks for this and also the Lutris version. Without you, I would not play LOL. :D
And sorry for bad English.

**Comment by GloriousEggroll** [comment]
thanks, these were just typos, fixed now
