### ISSUE TITLE
League Crashes after champ select patch 8.12

### ISSUE THREAD

**Issue by manning390** [GloriousEggroll/leagueoflegends-linux#11]
Game crashes after champion select, ver 8.12.233.818. It generates a tmp file (bug splat?) but it is encoded with something when I try to view the file. Not sure what else to report but I can get more information if needed.

Installed via the install.sh on Ubuntu Mate 18.04.

**Comment by GloriousEggroll** [comment]
not something I can fix.
https://www.reddit.com/r/linux_gaming/comments/8rjode/league_of_legends_to_end_all_forms_of_linux/
