### ISSUE TITLE
Bugsplat after champ select.

### ISSUE THREAD

**Issue by ikocevski** [GloriousEggroll/leagueoflegends-linux#2]
Hi, I'm on Arch Linux and I have wine-staging 2.21-1 installed with all of the deps listed on the Lutris site.

The system is i5/8G RAM/GTX650Ti. Using the proprietary nvidia driver.

I don't like using Lutris and I just used this part of your install script:
`WINEDEBUG=-all WINEPREFIX=/home/$USER/.wlol winetricks -q winxp directx9 d3dx9_41 d3dx9_42 d3dx9_43`
`WINEDEBUG=-all WINEPREFIX=/home/$USER/.wlol wine regedit /S lol.reg`
`WINEDEBUG=-all WINEPREFIX=/home/$USER/.wlol wine League\ of\ Legends\ installer\ NA.exe`

Then edited the game.cfg with vim to set the WindowMode=2

Made the launch script:
`#!/bin/bash`
`export __GL_THREADED_OPTIMIZATIONS=1`
`export VBLANK_MODE=0`
`WINEPREFIX=/home/$USER/.wlol WINEDEBUG=-all wine /mnt/hdd/Games/LoL/LeagueClient.exe`

And I just run the script with **sh** when I launch the game.
Everything works perfectly (it sets itself to low spec mode though) except when starting the game after champ select. It just shows bugsplat and all I can do is click don't send.

Don't know if this matters but I mount an NTFS partition to /mnt/hdd where the game is installed as you can see from the launch script. Also, my root partition is LUKS encrypted.

Tried editing the /etc/hosts file to set my hostname instead of localhost as the ArchWiki suggests but that didn't help.

**Comment by ikocevski** [comment]
Tried adding the DLL overrides listed on the Lutris script (atl120, msvcp120, vcomp120) but that didn't help either.

Tried removing `export VBLANK_MODE=0` from the launch script, also nothing.

Just FYI I have managed to run the game via Lutris before. Can't seem to get what I'm doing wrong here.

**Comment by GloriousEggroll** [comment]
either use my install script or use the lutris installer. don't try to do it by hand

**Comment by ikocevski** [comment]
After multiple tries to make the Wine configuration work it turns out that's not the issue at all. After the game crashes not only it shows a bugsplat, it also showed `libGL error: failed to load driver: swrast` on the terminal window.

I was actually missing **lib32-nvidia-utils** and that's why the game didn't start... otherwise neither the NTFS partition nor the LUKS encryption gave me an issue running the game.

Thanks for making League on Linux possible and sorry for wasting your time.

**Comment by GloriousEggroll** [comment]
np, glad you found the resolution, will mark as closed
