### ISSUE TITLE
League is broken after patch 8.6

### ISSUE THREAD

**Issue by Esteban-Rocha** [GloriousEggroll/leagueoflegends-linux#6]
Hi! I confirm League is utterly broken for lutris on arch after the voice update, I reinstalled twice and still the same, I turned off the voice feature too but no luck, applied wine dependency hell fix too on each installation too.

I'm using Wine Windows-DX9 version

Bug screen shows whenever LOL is going to start a match, client works, shop etc, but not even on training mode I can go in to the match.

I doubt it's my config I have been using it without issues until that update when everything went to hell. Would love if you can take a look at it.

BTW: thanks for your work at it!

**Comment by GloriousEggroll** [comment]
I've updated the lutris installer, please test.
it needs a new list of overrides:

api-ms-win-crt-conio-l1-1-0 (native, builtin)
api-ms-win-crt-heap-l1-1-0 (native, builtin)
api-ms-win-crt-locale-l1-1-0 (native, builtin)
api-ms-win-crt-math-l1-1-0 (native, builtin)
api-ms-win-crt-runtime-l1-1-0 (native, builtin)
api-ms-win-crt-stdio-l1-1-0 (native, builtin)
api-ms-win-crt-time-l1-1-0 (native, builtin)
atl140 (native, builtin)
concrt140 (native, builtin)
msvcp140 (native, builtin)
msvcr140 (native, builtin)
vcomp140 (native, builtin)
vcruntime140 (native, builtin)
ucrtbase (native, builtin)
devenum (native, builtin)
quartz (native, builtin)

only these, nothing else.

**Comment by Esteban-Rocha** [comment]
Thanks a lot! I'll test later for sure and let you know.

**Comment by GloriousEggroll** [comment]
fixed now. needed more than that. for a quick fix run regedit on the prefix and import lol.reg
