### ISSUE TITLE
No longer able to join game with wine-staging 3.5

### ISSUE THREAD

**Issue by M-Reimer** [GloriousEggroll/leagueoflegends-linux#7]
Maybe this is just a wine-staging bug and not possible to solve easily.
As soon as I've updated to wine-staging 3.5, I can use the client and do all my selections/choices. As soon as the "switch" between client and "game mode" should happen, the client only shows a "rejoin" button and the game itself does not start.
Immediately worked again as soon as I d9owngraded wine-staging.

**Comment by GloriousEggroll** [comment]
the required overrides have changed for 3.5. https://github.com/GloriousEggroll/leagueoflegends-linux/commit/2e457f41a05d6c435d527a4f8400b473e1ad54b7

youll want to run regedit on the prefix and import https://github.com/GloriousEggroll/leagueoflegends-linux/blob/master/lol.reg
