### ISSUE TITLE
Problems with wine-staging 3.5-1

### ISSUE THREAD

**Issue by TheJackiMonster** [GloriousEggroll/leagueoflegends-linux#8]
The new build of wine-staging (3.5-1) on Arch has some problems with league. The client works fine, but it can't open a game anymore. It directly seem to crash or maybe it can't open a connection. I don't know how to check the problem, but as long as this isn't solved, you need to use version 3.4-1.

So I don't know if the install-script could check the wine-version or something to even solve the problem. I am kind of curious, how an update of wine can have such results.

**Comment by GloriousEggroll** [comment]
please see closed issue https://github.com/GloriousEggroll/leagueoflegends-linux/issues/7
